web_port: 1080

climate:
  power: 7000
  min_run_time: 5
  max_run_time: 20
  loss3: 3100 # heatloss at -3C
  loss7: 1300 # heatloss at 7C
  internal_sensor_mac: "A4:C1:38:5C:18:A5"
  external_sensor_mac: "A4:C1:38:D1:64:5F"

ebus:
  host: "192.168.175.93"
  port: 8888
  circuit: "bai"
